language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
script: cd jobqueue && ./gradlew --stacktrace clean check --info
addons:
  artifacts: true
  s3_region: "us-west-1"
  debug: true
  paths:
      - $(ls jobqueue/build/outputs/* | tr "\n" ":")
      - $(ls jobqueue/build/reports/* | tr "\n" ":")

