package com.path.android.jobqueue.examples.twitter.entities;



// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import twitter4j.Status;
// KEEP INCLUDES END
/**
 * Entity mapped to table TWEET.
 */
public class Tweet extends TweetBase  {
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    public Tweet() {
    }

    public Tweet(Long localId) {
        super(localId);
    }

    public Tweet(Long localId, Long serverId, String text, Long userId, Boolean isLocal, java.util.Date createdAt) {
        super(localId, serverId, text, userId, isLocal, createdAt);
    }

    // KEEP METHODS - put your custom methods here
    public Tweet(Status status) {
        super(null, status.getId(), status.getText(), status.getUser().getId(), false, status.getCreatedAt());
    }

    @Override
    public void onBeforeSave() {
        isLocal = serverId == null;
        super.onBeforeSave();
    }
    // KEEP METHODS END

}
