package com.path.android.jobqueue;



// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.path.android.jobqueue.log.JqLog;

/**
 * Entity mapped to table JOB_HOLDER.
 */
public class JobHolder extends JobHolderBase  {
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    public JobHolder() {
    }

    public JobHolder(Long id) {
        super(id);
    }

    public JobHolder(Long id, Integer priority, Integer runCount, byte[] __baseJob, java.util.Date created, Long runningSessionId) {
        super(id, priority, runCount, __baseJob, created, runningSessionId);
    }

    // KEEP METHODS - put your custom methods here
    public final boolean safeRun(JobManager jobManager) {
        BaseJob baseJob = getBaseJob();
        if(baseJob == null) {
            return true;
        }
        return baseJob.safeRun(jobManager);
    }

    @Override
    public void onBeforeSave() {
        if(runningSessionId == null) {
            runningSessionId = Long.MIN_VALUE;
        }
        super.onBeforeSave();
    }

    // KEEP METHODS END

}
