package com.path.android.jobqueue.examples.twitter.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.path.android.jobqueue.examples.twitter.entities.Tweet;

import com.path.android.jobqueue.examples.twitter.dao.TweetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tweetDaoConfig;

    private final TweetDao tweetDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tweetDaoConfig = daoConfigMap.get(TweetDao.class).clone();
        tweetDaoConfig.initIdentityScope(type);

        tweetDao = new TweetDao(tweetDaoConfig, this);

        registerDao(Tweet.class, tweetDao);
    }

    public void clear() {
        tweetDaoConfig.getIdentityScope().clear();
    }

    public void deleteAllData() {
        tweetDao.deleteAll();
    }


    public TweetDao getTweetDao() {
        return tweetDao;
    }

}
