name: CI

on: [push, pull_request]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Build with Gradle
        run: ./gradlew check :jobqueue:createDebugCoverageReport --stacktrace